!function(e,t){if("object"==typeof exports&&"object"==typeof module)module.exports=t(require("fs"),require("path"));else if("function"==typeof define&&define.amd)define(["fs","path"],t);else{var n="object"==typeof exports?t(require("fs"),require("path")):t(e.fs,e.path);for(var o in n)("object"==typeof exports?exports:e)[o]=n[o]}}(this,function(e,t){return function(e){function t(o){if(n[o])return n[o].exports;var r=n[o]={exports:{},id:o,loaded:!1};return e[o].call(r.exports,r,r.exports,t),r.loaded=!0,r.exports}var n={};return t.m=e,t.c=n,t.p="",t(0)}([/*!**************************!*\
  !*** ./bin/src/index.js ***!
  \**************************/
function(e,t,n){"use strict";function o(){s.writeFile("src/posts/"+u+".md","# "+a.title+"\n<time datetime="+JSON.stringify(l)+">"+(l.getMonth()+1)+"/"+l.getDate()+"/"+l.getFullYear()+"</time>\n    ",function(e){return!e||(console.log(e),!1)})}function r(e,t,n){var o=e?c.reduce(function(o,r,s){return r.slug===e&&(r=Object.assign({},r,{title:t}),r.isDraft&&n&&(r.isDraft=!1)),o.push(r),o},[]):c.concat({isDraft:a.draft,postedDate:l,slug:u,title:a.title});s.writeFile("src/posts.json",JSON.stringify(o),function(e){return!e||(console.log(e),!1)})}var s=n(/*! fs */11),i=(n(/*! path */12),n(/*! chalk */3)),c=n(/*! ../../src/posts.json */6),a=Object.assign({},{draft:!1},n(/*! minimist */7)(process.argv.slice(2)));a.title||(console.error(i.red(i.bold("Error")+": to create a new post, you must provide a title.")),process.exit(1));var u=a.title.toLowerCase().replace(/\s/g,"-"),l=new Date;!function(){var e={update:a.update,postExists:c.map(function(e){return e.slug}).indexOf(u)!==-1,default:!0};switch(Object.keys(e).filter(function(t){return e[t]})[0]){case"update":r(a.update,a.title,a.publish);break;case"postExists":console.error(i.red(i.bold("Error:")+" A post with that title already exists. Please choose a new title."));break;default:var t=function(e){return new Promise(function(t,n){var o=e();o?n(o):t(o)})},n=t(o),s=t(r);n.then(s).then(console.log(i.green('Post: "'+a.title+'" successfully written and logged.')))}}()},/*!*******************************!*\
  !*** ./~/ansi-regex/index.js ***!
  \*******************************/
function(e,t){"use strict";e.exports=function(){return/[\u001b\u009b][[()#;?]*(?:[0-9]{1,4}(?:;[0-9]{0,4})*)?[0-9A-PRZcf-nqry=><]/g}},/*!********************************!*\
  !*** ./~/ansi-styles/index.js ***!
  \********************************/
function(e,t,n){(function(e){"use strict";function t(){var e={modifiers:{reset:[0,0],bold:[1,22],dim:[2,22],italic:[3,23],underline:[4,24],inverse:[7,27],hidden:[8,28],strikethrough:[9,29]},colors:{black:[30,39],red:[31,39],green:[32,39],yellow:[33,39],blue:[34,39],magenta:[35,39],cyan:[36,39],white:[37,39],gray:[90,39]},bgColors:{bgBlack:[40,49],bgRed:[41,49],bgGreen:[42,49],bgYellow:[43,49],bgBlue:[44,49],bgMagenta:[45,49],bgCyan:[46,49],bgWhite:[47,49]}};return e.colors.grey=e.colors.gray,Object.keys(e).forEach(function(t){var n=e[t];Object.keys(n).forEach(function(t){var o=n[t];e[t]=n[t]={open:"["+o[0]+"m",close:"["+o[1]+"m"}}),Object.defineProperty(e,t,{value:n,enumerable:!1})}),e}Object.defineProperty(e,"exports",{enumerable:!0,get:t})}).call(t,n(/*! ./../webpack/buildin/module.js */10)(e))},/*!**************************!*\
  !*** ./~/chalk/index.js ***!
  \**************************/
function(e,t,n){"use strict";function o(e){this.enabled=e&&void 0!==e.enabled?e.enabled:f}function r(e){var t=function(){return s.apply(t,arguments)};return t._styles=e,t.enabled=this.enabled,t.__proto__=g,t}function s(){var e=arguments,t=e.length,n=0!==t&&String(arguments[0]);if(t>1)for(var o=1;o<t;o++)n+=" "+e[o];if(!this.enabled||!n)return n;var r=this._styles,s=r.length,i=a.dim.open;for(!d||r.indexOf("gray")===-1&&r.indexOf("grey")===-1||(a.dim.open="");s--;){var c=a[r[s]];n=c.open+n.replace(c.closeRe,c.open)+c.close}return a.dim.open=i,n}function i(){var e={};return Object.keys(b).forEach(function(t){e[t]={get:function(){return r.call(this,[t])}}}),e}var c=n(/*! escape-string-regexp */4),a=n(/*! ansi-styles */2),u=n(/*! strip-ansi */8),l=n(/*! has-ansi */5),f=n(/*! supports-color */9),p=Object.defineProperties,d="win32"===process.platform&&!/^xterm/i.test({NODE_ENV:"production"}.TERM);d&&(a.blue.open="[94m");var b=function(){var e={};return Object.keys(a).forEach(function(t){a[t].closeRe=new RegExp(c(a[t].close),"g"),e[t]={get:function(){return r.call(this,this._styles.concat(t))}}}),e}(),g=p(function(){},b);p(o.prototype,i()),e.exports=new o,e.exports.styles=a,e.exports.hasColor=l,e.exports.stripColor=u,e.exports.supportsColor=f},/*!*****************************************!*\
  !*** ./~/escape-string-regexp/index.js ***!
  \*****************************************/
function(e,t){"use strict";var n=/[|\\{}()[\]^$+*?.]/g;e.exports=function(e){if("string"!=typeof e)throw new TypeError("Expected a string");return e.replace(n,"\\$&")}},/*!*****************************!*\
  !*** ./~/has-ansi/index.js ***!
  \*****************************/
function(e,t,n){"use strict";var o=n(/*! ansi-regex */1),r=new RegExp(o().source);e.exports=r.test.bind(r)},/*!************************!*\
  !*** ./src/posts.json ***!
  \************************/
function(e,t){e.exports=[]},/*!*****************************!*\
  !*** ./~/minimist/index.js ***!
  \*****************************/
function(e,t){function n(e,t){var n=e;t.slice(0,-1).forEach(function(e){n=n[e]||{}});var o=t[t.length-1];return o in n}function o(e){return"number"==typeof e||!!/^0x[0-9a-f]+$/i.test(e)||/^[-+]?(?:\d+(?:\.\d*)?|\.\d+)(e[-+]?\d+)?$/.test(e)}e.exports=function(e,t){function r(e,t){return a.allBools&&/^--[^=]+$/.test(t)||a.strings[e]||a.bools[e]||u[e]}function s(e,t,n){if(!n||!a.unknownFn||r(e,n)||a.unknownFn(n)!==!1){var s=!a.strings[e]&&o(t)?Number(t):t;i(f,e.split("."),s),(u[e]||[]).forEach(function(e){i(f,e.split("."),s)})}}function i(e,t,n){var o=e;t.slice(0,-1).forEach(function(e){void 0===o[e]&&(o[e]={}),o=o[e]});var r=t[t.length-1];void 0===o[r]||a.bools[r]||"boolean"==typeof o[r]?o[r]=n:Array.isArray(o[r])?o[r].push(n):o[r]=[o[r],n]}function c(e){return u[e].some(function(e){return a.bools[e]})}t||(t={});var a={bools:{},strings:{},unknownFn:null};"function"==typeof t.unknown&&(a.unknownFn=t.unknown),"boolean"==typeof t.boolean&&t.boolean?a.allBools=!0:[].concat(t.boolean).filter(Boolean).forEach(function(e){a.bools[e]=!0});var u={};Object.keys(t.alias||{}).forEach(function(e){u[e]=[].concat(t.alias[e]),u[e].forEach(function(t){u[t]=[e].concat(u[e].filter(function(e){return t!==e}))})}),[].concat(t.string).filter(Boolean).forEach(function(e){a.strings[e]=!0,u[e]&&(a.strings[u[e]]=!0)});var l=t.default||{},f={_:[]};Object.keys(a.bools).forEach(function(e){s(e,void 0!==l[e]&&l[e])});var p=[];e.indexOf("--")!==-1&&(p=e.slice(e.indexOf("--")+1),e=e.slice(0,e.indexOf("--")));for(var d=0;d<e.length;d++){var b=e[d];if(/^--.+=/.test(b)){var g=b.match(/^--([^=]+)=([\s\S]*)$/),h=g[1],v=g[2];a.bools[h]&&(v="false"!==v),s(h,v,b)}else if(/^--no-.+/.test(b)){var h=b.match(/^--no-(.+)/)[1];s(h,!1,b)}else if(/^--.+/.test(b)){var h=b.match(/^--(.+)/)[1],y=e[d+1];void 0===y||/^-/.test(y)||a.bools[h]||a.allBools||u[h]&&c(h)?/^(true|false)$/.test(y)?(s(h,"true"===y,b),d++):s(h,!a.strings[h]||"",b):(s(h,y,b),d++)}else if(/^-[^-]+/.test(b)){for(var x=b.slice(1,-1).split(""),E=!1,m=0;m<x.length;m++){var y=b.slice(m+2);if("-"!==y){if(/[A-Za-z]/.test(x[m])&&/=/.test(y)){s(x[m],y.split("=")[1],b),E=!0;break}if(/[A-Za-z]/.test(x[m])&&/-?\d+(\.\d*)?(e-?\d+)?$/.test(y)){s(x[m],y,b),E=!0;break}if(x[m+1]&&x[m+1].match(/\W/)){s(x[m],b.slice(m+2),b),E=!0;break}s(x[m],!a.strings[x[m]]||"",b)}else s(x[m],y,b)}var h=b.slice(-1)[0];E||"-"===h||(!e[d+1]||/^(-|--)[^-]/.test(e[d+1])||a.bools[h]||u[h]&&c(h)?e[d+1]&&/true|false/.test(e[d+1])?(s(h,"true"===e[d+1],b),d++):s(h,!a.strings[h]||"",b):(s(h,e[d+1],b),d++))}else if(a.unknownFn&&a.unknownFn(b)===!1||f._.push(a.strings._||!o(b)?b:Number(b)),t.stopEarly){f._.push.apply(f._,e.slice(d+1));break}}return Object.keys(l).forEach(function(e){n(f,e.split("."))||(i(f,e.split("."),l[e]),(u[e]||[]).forEach(function(t){i(f,t.split("."),l[e])}))}),t["--"]?(f["--"]=new Array,p.forEach(function(e){f["--"].push(e)})):p.forEach(function(e){f._.push(e)}),f}},/*!*******************************!*\
  !*** ./~/strip-ansi/index.js ***!
  \*******************************/
function(e,t,n){"use strict";var o=n(/*! ansi-regex */1)();e.exports=function(e){return"string"==typeof e?e.replace(o,""):e}},/*!***********************************!*\
  !*** ./~/supports-color/index.js ***!
  \***********************************/
function(e,t,n){"use strict";var o=process.argv,r=o.indexOf("--"),s=function(e){e="--"+e;var t=o.indexOf(e);return t!==-1&&(r===-1||t<r)};e.exports=function(){return"FORCE_COLOR"in{NODE_ENV:"production"}||!(s("no-color")||s("no-colors")||s("color=false"))&&(!!(s("color")||s("colors")||s("color=true")||s("color=always"))||!(process.stdout&&!process.stdout.isTTY)&&("win32"===process.platform||"COLORTERM"in{NODE_ENV:"production"}||"dumb"!=={NODE_ENV:"production"}.TERM&&!!/^screen|^xterm|^vt100|color|ansi|cygwin|linux/i.test({NODE_ENV:"production"}.TERM)))}()},/*!***********************************!*\
  !*** (webpack)/buildin/module.js ***!
  \***********************************/
function(e,t){e.exports=function(e){return e.webpackPolyfill||(e.deprecate=function(){},e.paths=[],e.children=[],e.webpackPolyfill=1),e}},/*!*********************!*\
  !*** external "fs" ***!
  \*********************/
function(e,t){e.exports=require("fs")},/*!***********************!*\
  !*** external "path" ***!
  \***********************/
function(e,t){e.exports=require("path")}])});
//# sourceMappingURL=app.js.map